### ISSUE TITLE
Cannot work with ESurfingClient V3.39

### ISSUE THREAD

**Issue by Zecozhang** [CrystallineDW/SchoolEsurfingHotspot#2]
date: 2019/05/20
after run the .vbs file and start hotspot, network disconnected

**Comment by Zecozhang** [comment]
After a `git pull` make it up-to-date, it said missing some .dll files

> msvcp140d.dll

> vcruntime140d.dll

**Comment by CrystallineDW** [comment]
Code compilation problem, fixed
